-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-06-06 00:33:25 NZST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c


set echo on
spool fdas_schema_output.txt

DROP TABLE assessor CASCADE CONSTRAINTS;

DROP TABLE building CASCADE CONSTRAINTS;

DROP TABLE building_damage CASCADE CONSTRAINTS;

DROP TABLE claim CASCADE CONSTRAINTS;

DROP TABLE employment_history CASCADE CONSTRAINTS;

DROP TABLE fire CASCADE CONSTRAINTS;

DROP TABLE insurer CASCADE CONSTRAINTS;

DROP TABLE lga CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE property CASCADE CONSTRAINTS;

DROP TABLE report CASCADE CONSTRAINTS;

DROP TABLE visit CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE assessor (
    assessor_id               NUMBER(7) NOT NULL,
    assessor_contact_number   NUMBER(10) NOT NULL,
    assessor_given_name       VARCHAR2(10),
    assessor_last_name        VARCHAR2(10),
    assessor_current_employer VARCHAR2(15) NOT NULL,
    assessor_start_date       DATE NOT NULL,
    assessor_end_date         DATE,
    insurance_code            NUMBER(7) NOT NULL
);

COMMENT ON COLUMN assessor.assessor_id IS
    'assessor ID number';

COMMENT ON COLUMN assessor.assessor_contact_number IS
    'Assessor contact number';

COMMENT ON COLUMN assessor.assessor_given_name IS
    'Assessor Given Name';

COMMENT ON COLUMN assessor.assessor_last_name IS
    'Assessor''s Last name';

COMMENT ON COLUMN assessor.assessor_current_employer IS
    'The current name of the assessor''s employer';

COMMENT ON COLUMN assessor.assessor_start_date IS
    'Date of employment start';

COMMENT ON COLUMN assessor.assessor_end_date IS
    'Date that assessor ended employment with current employer';

COMMENT ON COLUMN assessor.insurance_code IS
    'Insurer code number';

ALTER TABLE assessor ADD CONSTRAINT assessor_pk PRIMARY KEY ( assessor_id );

CREATE TABLE building (
    building_id            NUMBER(1) NOT NULL,
    building_approved_date DATE,
    building_size          NUMBER(5, 2),
    building_class         NUMBER(2),
    property_id            NUMBER(7) NOT NULL,
    insurance_code         NUMBER(7)
);

COMMENT ON COLUMN building.building_id IS
    'Building ID';

COMMENT ON COLUMN building.building_approved_date IS
    'Date the building was approved for construction';

COMMENT ON COLUMN building.building_size IS
    'Size of the building in metre square';

COMMENT ON COLUMN building.building_class IS
    'Building Class';

COMMENT ON COLUMN building.property_id IS
    'Property ID';

COMMENT ON COLUMN building.insurance_code IS
    'Insurer code number';

ALTER TABLE building ADD CONSTRAINT building_pk PRIMARY KEY ( building_id,
                                                              property_id );

CREATE TABLE building_damage (
    claim_code            NUMBER(7) NOT NULL,
    bd_cost               NUMBER(100000000, 2),
    bd_totally_destroyed  CHAR(1),
    bd_insurance_coverage CHAR(1) NOT NULL,
    building_id           NUMBER(1) NOT NULL,
    property_id           NUMBER(7) NOT NULL
);

ALTER TABLE building_damage
    ADD CHECK ( bd_totally_destroyed IN ( 'N', 'Y' ) );

ALTER TABLE building_damage
    ADD CHECK ( bd_insurance_coverage IN ( 'N', 'Y' ) );

COMMENT ON COLUMN building_damage.claim_code IS
    'Insurance claim code';

COMMENT ON COLUMN building_damage.bd_cost IS
    'Cost of building damage';

COMMENT ON COLUMN building_damage.bd_totally_destroyed IS
    'Building destroyed totally? Y/N';

COMMENT ON COLUMN building_damage.bd_insurance_coverage IS
    'Does the building have insurance? Y/N';

COMMENT ON COLUMN building_damage.building_id IS
    'Building ID';

COMMENT ON COLUMN building_damage.property_id IS
    'Property ID';

ALTER TABLE building_damage ADD CONSTRAINT building_damage_pk PRIMARY KEY ( building_id
,
                                                                            property_id
                                                                            );

CREATE TABLE claim (
    claim_code  NUMBER(7) NOT NULL,
    building_id NUMBER(1) NOT NULL,
    owner_id    NUMBER(6) NOT NULL,
    assessor_id NUMBER(7) NOT NULL
);

COMMENT ON COLUMN claim.claim_code IS
    'Claim code for insurance ';

COMMENT ON COLUMN claim.building_id IS
    'Building ID number';

COMMENT ON COLUMN claim.owner_id IS
    'Owner ID';

COMMENT ON COLUMN claim.assessor_id IS
    'assessor ID number';

ALTER TABLE claim ADD CONSTRAINT claim_pk PRIMARY KEY ( claim_code,
                                                        assessor_id );

CREATE TABLE employment_history (
    eh_past_employer       VARCHAR2(15),
    eh_past_employer_start DATE NOT NULL,
    eh_past_employer_end   DATE NOT NULL,
    assessor_id            NUMBER(7) NOT NULL
);

COMMENT ON COLUMN employment_history.eh_past_employer IS
    'Previous employer';

COMMENT ON COLUMN employment_history.eh_past_employer_start IS
    'Start date of last employer';

COMMENT ON COLUMN employment_history.eh_past_employer_end IS
    'End date of previous employment';

COMMENT ON COLUMN employment_history.assessor_id IS
    'assessor ID number';

ALTER TABLE employment_history ADD CONSTRAINT emplyoment_history_pk PRIMARY KEY ( assessor_id
);

CREATE TABLE fire (
    fire_id             NUMBER(10) NOT NULL,
    fire_name           VARCHAR2(35) NOT NULL,
    fire_start_date     DATE NOT NULL,
    fire_latitude       NUMBER(9, 7) NOT NULL,
    fire_longitude      NUMBER(10, 7) NOT NULL,
    fire_hectares_burnt NUMBER(1000000000) NOT NULL,
    fire_lives_lost     VARCHAR2(100),
    fire_total_damage   NUMBER(1000000000),
    property_id         NUMBER(7) NOT NULL
);

COMMENT ON COLUMN fire.fire_id IS
    'Fire event ID';

COMMENT ON COLUMN fire.fire_name IS
    'the name of the Fire event';

COMMENT ON COLUMN fire.fire_start_date IS
    'start date of the fire event';

COMMENT ON COLUMN fire.fire_latitude IS
    'Latitude coordinates of the fire';

COMMENT ON COLUMN fire.fire_longitude IS
    'Longitude coordinates of the fire';

COMMENT ON COLUMN fire.fire_hectares_burnt IS
    'Numbers of any hectares burnt in the fire';

COMMENT ON COLUMN fire.fire_lives_lost IS
    'number of lives lost';

COMMENT ON COLUMN fire.fire_total_damage IS
    'total cost of fire damage';

COMMENT ON COLUMN fire.property_id IS
    'property number ID';

CREATE UNIQUE INDEX fire__idx ON
    fire (
        property_id
    ASC );

ALTER TABLE fire ADD CONSTRAINT fire_pk PRIMARY KEY ( fire_id );

CREATE TABLE insurer (
    insurance_code         NUMBER(7) NOT NULL,
    insurer_name           VARCHAR2(15) NOT NULL,
    insurer_contact_number NUMBER(10) NOT NULL
);

COMMENT ON COLUMN insurer.insurance_code IS
    'Insurer code number';

COMMENT ON COLUMN insurer.insurer_name IS
    'Name of insurer';

COMMENT ON COLUMN insurer.insurer_contact_number IS
    'Phone number of insurer';

ALTER TABLE insurer ADD CONSTRAINT insurer_pk PRIMARY KEY ( insurance_code );

CREATE TABLE lga (
    lga_id             NUMBER(10) NOT NULL,
    lga_name           VARCHAR2(25) NOT NULL,
    lga_size           VARCHAR2(1000) NOT NULL,
    lga_ceo            VARCHAR2(40) NOT NULL,
    lga_contact_number CHAR(10) NOT NULL,
    fire_id            NUMBER(10)
);

COMMENT ON COLUMN lga.lga_id IS
    'LGA identification number';

COMMENT ON COLUMN lga.lga_name IS
    'name of the LGA';

COMMENT ON COLUMN lga.lga_size IS
    'size in hectares of the LGA';

COMMENT ON COLUMN lga.lga_ceo IS
    'name of the LGA CEO';

COMMENT ON COLUMN lga.lga_contact_number IS
    'contact phone number of the LGA';

COMMENT ON COLUMN lga.fire_id IS
    'Fire event ID';

ALTER TABLE lga ADD CONSTRAINT lga_pk PRIMARY KEY ( lga_id );

CREATE TABLE owner (
    owner_id          NUMBER(6) NOT NULL,
    owner_name        VARCHAR2(20) NOT NULL,
    owner_phonenumber CHAR(10) NOT NULL
);

COMMENT ON COLUMN owner.owner_id IS
    'Owner ID number';

COMMENT ON COLUMN owner.owner_name IS
    'Owner name';

COMMENT ON COLUMN owner.owner_phonenumber IS
    'Owner Phone Number';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE property (
    property_id       NUMBER(7) NOT NULL,
    property_street   VARCHAR2(30) NOT NULL,
    property_town     VARCHAR2(20) NOT NULL,
    property_postcode NUMBER(4) NOT NULL,
    lga_id            NUMBER(10) NOT NULL,
    owner_id          NUMBER(6) NOT NULL
);

COMMENT ON COLUMN property.property_id IS
    'Property ID';

COMMENT ON COLUMN property.property_street IS
    'Street the property is on';

COMMENT ON COLUMN property.property_town IS
    'Town the property is located in';

COMMENT ON COLUMN property.property_postcode IS
    'Postcode for that property';

COMMENT ON COLUMN property.lga_id IS
    'LGA identification number';

COMMENT ON COLUMN property.owner_id IS
    'Owner ID number';

ALTER TABLE property ADD CONSTRAINT property_pk PRIMARY KEY ( property_id );

CREATE TABLE report (
    property_id NUMBER(7) NOT NULL,
    fire_id     NUMBER(10) NOT NULL
);

COMMENT ON COLUMN report.property_id IS
    'property number ID';

COMMENT ON COLUMN report.fire_id IS
    'Fire event ID';

CREATE UNIQUE INDEX report__idx ON
    report (
        fire_id
    ASC );

ALTER TABLE report ADD CONSTRAINT report_pk PRIMARY KEY ( property_id );

CREATE TABLE visit (
    visit_id            NUMBER(7) NOT NULL,
    fire_id             NUMBER(10) NOT NULL,
    date_time_arrival   DATE,
    date_time_departure DATE,
    property_id         NUMBER(7) NOT NULL,
    assessor_id         NUMBER(7) NOT NULL
);

COMMENT ON COLUMN visit.visit_id IS
    'Visit ID';

COMMENT ON COLUMN visit.fire_id IS
    'Fire event ID';

COMMENT ON COLUMN visit.date_time_arrival IS
    'Date and time of arrival';

COMMENT ON COLUMN visit.date_time_departure IS
    'Date and time of departure';

COMMENT ON COLUMN visit.property_id IS
    'Property ID';

COMMENT ON COLUMN visit.assessor_id IS
    'assessor ID number';

ALTER TABLE visit
    ADD CONSTRAINT visit_pk PRIMARY KEY ( visit_id,
                                          property_id,
                                          assessor_id );

ALTER TABLE claim
    ADD CONSTRAINT assessor_claim FOREIGN KEY ( assessor_id )
        REFERENCES assessor ( assessor_id );

ALTER TABLE employment_history
    ADD CONSTRAINT assessor_eh FOREIGN KEY ( assessor_id )
        REFERENCES assessor ( assessor_id );

ALTER TABLE visit
    ADD CONSTRAINT assesssor_visit FOREIGN KEY ( assessor_id )
        REFERENCES assessor ( assessor_id );

ALTER TABLE building_damage
    ADD CONSTRAINT building_building_damage FOREIGN KEY ( building_id,
                                                          property_id )
        REFERENCES building ( building_id,
                              property_id );

ALTER TABLE lga
    ADD CONSTRAINT fire_lga FOREIGN KEY ( fire_id )
        REFERENCES fire ( fire_id );

ALTER TABLE report
    ADD CONSTRAINT fire_report FOREIGN KEY ( fire_id )
        REFERENCES fire ( fire_id );

ALTER TABLE fire
    ADD CONSTRAINT fire_reportv1 FOREIGN KEY ( property_id )
        REFERENCES report ( property_id );

ALTER TABLE assessor
    ADD CONSTRAINT insurer_assesor FOREIGN KEY ( insurance_code )
        REFERENCES insurer ( insurance_code );

ALTER TABLE building
    ADD CONSTRAINT insurer_building FOREIGN KEY ( insurance_code )
        REFERENCES insurer ( insurance_code );

ALTER TABLE property
    ADD CONSTRAINT lga_property FOREIGN KEY ( lga_id )
        REFERENCES lga ( lga_id );

ALTER TABLE property
    ADD CONSTRAINT owner_property FOREIGN KEY ( owner_id )
        REFERENCES owner ( owner_id );

ALTER TABLE building
    ADD CONSTRAINT property_building FOREIGN KEY ( property_id )
        REFERENCES property ( property_id );

ALTER TABLE visit
    ADD CONSTRAINT property_visit FOREIGN KEY ( property_id )
        REFERENCES property ( property_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             2
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL OFF
SET ECHO OFF